# Generated by Django 6.0.5 on 2026-05-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
