# Generated by Django 6.0.5 on 2026-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0005_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
