# Generated by Django 6.0.5 on 2026-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0007_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
