# Generated by Django 6.0.5 on 2026-06-01 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0008_alter_inquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=120)),
                ('university_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Leave empty if you are still pursuing this degree.', null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 8.70', max_digits=4, null=True)),
                ('description', models.TextField()),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Skills or subjects covered (comma-separated in admin).')),
                ('status', models.CharField(choices=[('pursuing', 'Pursuing'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first on the portfolio.')),
                ('duration_label', models.CharField(blank=True, help_text="Optional override, e.g. '3 Years' or 'Ongoing'.", max_length=40)),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide this entry on the public site.')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-display_order', '-start_year'],
            },
        ),
    ]
