# Generated by Django 6.0.5 on 2026-06-01 13:33

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import mainportfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0010_seed_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['display_order', 'link_name']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-display_order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['category', '-display_order', 'skill_name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first.'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from the public site.'),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first within a category.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[mainportfolio.validators.validate_cgpa]),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[mainportfolio.validators.validate_education_year]),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(validators=[mainportfolio.validators.validate_education_year]),
        ),
        migrations.AlterField(
            model_name='education',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), mainportfolio.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['is_visible', '-display_order'], name='mainportfol_is_visi_92da62_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['status'], name='mainportfol_status_4e8085_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at'], name='mainportfol_created_98168f_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['email'], name='mainportfol_email_88bcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['display_order', 'is_visible'], name='mainportfol_display_599d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['-display_order', 'is_published'], name='mainportfol_display_b40ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['category', '-display_order'], name='mainportfol_categor_b1dd74_idx'),
        ),
    ]
