# Generated by Django 6.0.5 on 2026-07-04 06:52

import django.core.validators
import django.db.models.deletion
import mainportfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportfolio', '0011_enhance_models_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, default='Web Development', help_text='Project category (e.g., Web Development, Mobile App, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for the modal popup. If empty, uses description.', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AddField(
            model_name='projects',
            name='live_url',
            field=models.URLField(blank=True, default='', help_text='URL to live demo or deployed project'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_year',
            field=models.CharField(blank=True, help_text='e.g., 2024 or 2024-2025', max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), mainportfolio.validators.validate_image_file_size])),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first in the gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='The project this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainportfolio.projects')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['project', 'display_order'], name='mainportfol_project_4e0840_idx')],
            },
        ),
    ]
